#-------------------------------------------------------------
# Manifest File to create Deployment with Labels and ReplicaSet
#
# Created by Vitalii Storozh 2021
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app  : my-k8s-application
    env  : prod
    owner: VitaliiStorozh
spec:
  replicas: 3
  selector:
    matchLabels:
      project: next
  template:
    metadata:
      labels:
        project: next
    spec:
      containers:
        - name : next-web
          image: httpd:latest
          ports:
            - containerPort: 80
